### ISSUE TITLE
Request new release

### ISSUE THREAD

**Issue by bparry02** [rhtconsulting/ansible-redhat_openshift_utils#10]
@itewk can we please get a new release of this repo that includes all of the recent changes to the playbooks? e.g. v3.1

**Comment by itewk** [comment]
@bparry02 ill do you one better. you are now an admin of this project. go nuts.

**Comment by bparry02** [comment]
@itewk I tried pushing a new tag but I'm getting access denied.

**Comment by bparry02** [comment]
Access is working now, thanks!

Created release [v3.1](https://github.com/RedHatOfficial/ansible-redhat_openshift_utils/releases/tag/v3.1)
