### ISSUE TITLE
Yum update fails with large number of packages and kernel updates

### ISSUE THREAD

**Issue by bparry02** [rhtconsulting/ansible-redhat_openshift_utils#13]
It is possible that the os-update-and-upgrade playbook will fail if the yum update takes too long. This can be caused by a large number of packages to update, or some kernel updates (e.g. >5 mins).

Implement one or both of the following changes:

- separate yum update of kernel from the rest of the packages. A flag could be used to disable kernel updates entirely
- try adding the async and poll attributes to the yum task: https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html

**Comment by itewk** [comment]
iv never seen it fail before even when the package update takes 10+ minutes. This wouldn't be ansible thats failing, it would be some timeout with your ssh connection.
